= Exploring The Windows Node

Now that you've learned how to manage a Windows Node, we will explore how this
node is set up. You can access this Windows node via the same mechanism
as the WMCO, via SSH.

Since this cluster was installed in the cloud, the Windows Node isn't
exposed to the public internet. So we will need to deploy an ssh bastion Pod.

NOTE: For information on how to enable RDP on an AWS instance, please see the link:https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html[official documentation] on their website.

The ssh bastion pod can be deployed using the Deployment YAML provided to you in this lab.

[source,bash,role="execute"]
----
oc apply -n openshift-windows-machine-config-operator -f ~/support/win-node-ssh.yaml
----

You can wait for the rollout of this ssh bastion pod.

[source,bash,role="execute"]
----
oc rollout status deploy/winc-ssh -n openshift-windows-machine-config-operator
----

Once rolled out, you should have the ssh bastion pod running.

[source,bash,role="execute"]
----
oc get pods -n openshift-windows-machine-config-operator -l app=winc-ssh
----

The ssh bastion pod mounts the ssh key needed to login to the Windows Node.

[source,bash,role="execute"]
----
yq e '.spec.template.spec.volumes' ~/support/win-node-ssh.yaml
----

In order to be able to ssh into this node you will need the hostname. Get
this hostname with the following command and make note of it.

[source,bash,role="execute"]
----
oc get nodes -l kubernetes.io/os=windows
----

Now open a bash session into the ssh bastion pod using the `oc exec` command.

[source,bash,role="execute"]
----
oc exec -it deploy/winc-ssh -n openshift-windows-machine-config-operator -- bash
----

Use the provided `sshcmd.sh` command built into the pod to login to the
Windows Node. Here is an example:

[source,bash]
----
bash-4.4$ sshcmd.sh ip-10-0-20-199.us-east-2.compute.internal
----

This should drop you into a PowerShell session. It should look something like this.

[source,bash]
----
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator>
----

Once on the Windows Node, you can see the `containerd`, `hybrid-overlay-node`, `kubelet`, `kube-proxy`,
`windows_exporter` and `windows-instance-config-daemon` processes are running.

[source,bash,role="execute"]
----
Get-Process | ?{ $_.ProcessName -match "daemon|exporter|kube|overlay|containerd" }
----

You should see the following output.

[source,bash]
----
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    173      14    31488      36740       5.97   4688   0 containerd
    254      17    31080      40376       2.48   5320   0 hybrid-overlay-node
    482      31    56224      80748      46.11   1924   0 kubelet
    101       8    12704       6096       0.09   5100   0 kube-log-runner
    104       8    12424       5332       0.11   5440   0 kube-log-runner
    268      21    33176      44792       3.80   6080   0 kube-proxy
    436      23    30824      32440      20.22   2676   0 windows_exporter
    209      15    26252      85528       4.23   3056   0 windows-instance-config-daemon
----

These are the main components needed to run a Windows Node. Remember that
this node is managed the same way as a Linux node, Via the MachineAPI;
so you won't have to do much with this Windows Node.

You can now exit out of the PowerShell session.

[source,bash,role="execute"]
----
exit
----

You can also exit out of the bash container session as well.

[source,bash,role="execute"]
----
exit
----

