= Installing a Windows Node

In order for the WMCO to setup the Windows Node, it will need an ssh key
to the cloud provider. The cloud provider will then mint a new keypair
based on the private key provided. The WMCO will then use this key to
login to the Windows Node and set it up as an OpenShift Node.

Generate an ssh key for the WMCO to use:

[source,bash,role="execute"]
----
ssh-keygen -t rsa -f ${HOME}/.ssh/winkey -q -N ''
----

Once you've generated the key, add it as a secret to the
`openshift-windows-machine-config-operator` namespace.

[source,bash,role="execute"]
----
oc create secret generic cloud-private-key --from-file=private-key.pem=${HOME}/.ssh/winkey -n openshift-windows-machine-config-operator 
----

This secret is used by the WMCO Operator to setup the Windows Node. Verify
that it was created before you proceed.

[source,bash,role="execute"]
----
oc get secret -n openshift-windows-machine-config-operator cloud-private-key
----

Once the WMCO Operator is up and running, and the ssh key loaded into
the cluster as a secret, you can now deploy a Windows Node. How do you
build a Windows Node? The same way you create OpenShift Linux nodes,
with the MachineAPI

NOTE: The MachineAPI allows you to manage compute resources in OpenShift. You'll learn about creating MachineSets, which define templates for creating multiple identical Machines (VMs) that become Nodes in your cluster.

First, we will be creating a MachineSet for Windows Nodes. We will then
explore important sections of the YAML.

[source,bash,role="execute"]
----
${HOME}/support/generate-windows-ms.sh
----

NOTE: For more information on how to create a Windows MachineSet YAML see the link:https://docs.openshift.com/container-platform/4.16/windows_containers/creating_windows_machinesets/creating-windows-machineset-aws.html[official docs].

This should create the `windows-ms.yaml` file in your home directory.

[source,bash,role="execute"]
----
ls -l ~/windows-ms.yaml
----

NOTE: Feel free to take a look at the file if you wish. You'll see that it doesn't differ from a Linux MachineSet.

The Windows MachineSet is labeled with an Operating System ID of `Windows`. The following command will show the label of `machine.openshift.io/os-id: Windows` for the MachineSet.

[source,bash,role="execute"]
----
yq e '.metadata.labels' ~/windows-ms.yaml
----

All the Windows Machines will have the `worker` label. The Windows Node
will be treated like any other node in the cluster.

[source,bash,role="execute"]
----
yq e '.spec.template.spec.metadata.labels' ~/windows-ms.yaml
----

The AMI ID is of a Windows Server 2019 AMI.

[source,bash,role="execute"]
----
yq e '.spec.template.spec.providerSpec.value.ami.id' ~/windows-ms.yaml
----

NOTE: You will need to use an AMI of a supported version of Windows Server. For more information, consult the link:https://docs.openshift.com/container-platform/4.15/windows_containers/wmco_rn/windows-containers-release-notes-10-15-x.html#supported-windows-server-versions[official documentation].

One last thing to note, is the user data secret.

[source,bash,role="execute"]
----
yq e '.spec.template.spec.providerSpec.value.userDataSecret.name' ~/windows-ms.yaml
----

This secret is generated by the WMCO when it was installed.

[source,bash,role="execute"]
----
oc get secret windows-user-data -n openshift-machine-api
----

Apply the YAML to create the Windows MachineSet on the cluster.

[source,bash,role="execute"]
----
oc apply -f ~/windows-ms.yaml
----

You can now see the status of the MachineSet.

[source,bash,role="execute"]
----
oc get machinesets  -n openshift-machine-api -l machine.openshift.io/os-id=Windows
----

This should show the following output.

[source,bash]
----
NAME                                            DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-w2tlt-7rwdh-windows-worker-us-east-2a     1         1                             9s
----

The MachineSet has the replica set to 1. The MachineAPI will see that desired state and, in turn, create a Windows Machine. This machine will eventually turn into a node. See the status of the machine with the following command.

[source,bash,role="execute"]
----
oc get machines  -n openshift-machine-api -l machine.openshift.io/os-id=Windows
----

Once the Machine is up and running, the WMCO will configure it. You can follow that status by looking at the WMCO pod log.

[source,bash,role="execute"]
----
oc logs -l name=windows-machine-config-operator -n openshift-windows-machine-config-operator   -f
----

You can exit by pressing kbd:[Ctrl+C].

NOTE: If you wish, you can wait until you see "Windows VM has been configured as a worker node" log message. Otherwise, go ahead and break out of following the log.

This Machine will create a Windows Node and the WMCO will add it to the cluster. You
can see the node with the following command.

[source,bash,role="execute"]
----
oc get nodes -l kubernetes.io/os=windows
----

NOTE: It'll take up to 15 mintues to see the Windows Node appear. It's recommneded to run a `watch` on `oc get nodes -l kubernetes.io/os=windows` so you can see when the node appears. Now will be a good time to take a break.

The output should look something like this.

[source,bash]
----
NAME                                        STATUS   ROLES    AGE   VERSION
ip-10-0-12-4.us-east-2.compute.internal     Ready    worker   25m    v1.29.6+aba1e8d
----

